# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125JwIQ9k5LKpDmOurWtl3kAN2eA24ASa
"""

# main.py

def greet(name: str) -> str:
    """Return a greeting message."""
    return f"Hello, {name}! Welcome to GitHub 🚀"

def main():
    user_name = input("Enter your name: ")
    message = greet(user_name)
    print(message)

if __name__ == "__main__":
    main()