# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125JwIQ9k5LKpDmOurWtl3kAN2eA24ASa
"""

print("hwllpo world")